name: Build server

on:
  push:
    paths:
      - '.github/workflows/server.yml'
      - 'app/**'
      - 'conf/**'
      - 'modules/**'
      - 'project/**'
      - 'translation/**'
      - 'build.sbt'
      - 'lila'
      - 'conf/application.conf.default'
      - '.sbtopts.default'
    branches-ignore:
      - 'l10n_master'
  pull_request:
    paths:
      - '.github/workflows/server.yml'
      - 'app/**'
      - 'conf/**'
      - 'modules/**'
      - 'project/**'
      - 'translation/source/**'
      - 'build.sbt'
      - 'lila'
      - 'conf/application.conf.default'
      - '.sbtopts.default'

jobs:
  openjdk14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Mind-Sports-Games/lila-maven
        uses: actions/checkout@v2
        with:
          repository: Mind-Sports-Games/lila-maven
          ref: refs/heads/master
          # GitHub's personal access token with access to `Mind-Sports-Games/lila-maven`
          token: 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
          persist-credentials: false
          path: ./.github/lila-maven
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
      - run: ls /home/runner/work/lila/
          java-version: 14.0.1
      - run: ls /home/runner/work/lila/lila/
      - run: ls /home/runner/work/lila/lila/.github/
      - run: ls /home/runner/work/lila/lila/.github/
      - run: ls /home/runner/work/lila/lila/.github/lila-maven/
      - run: ls /home/runner/work/lila/lila/.github/lila-maven/org/
      - run: ls /home/runner/work/lila/lila/.github/lila-maven/org/lichess/
      - run: ls /home/runner/work/lila/lila/.github/lila-maven/org/lichess/scalachess_2.13/
      - run: ls /home/runner/work/lila/lila/.github/lila-maven/org/lichess/scalachess_2.13/10.2.1/
      - run: TZ=UTC git log -1 --date=iso-strict-local --pretty='format:app.version.commit = "%h"%napp.version.date = "%ad"%napp.version.message = """%s"""%n' | tee conf/version.conf
      - run: ./lila -Depoll=true "test;stage"
      - run: cp LICENSE COPYING.md README.md target/universal/stage && git log -n 1 --pretty=oneline > target/universal/stage/commit.txt
      - run: cd target/universal/stage && tar -cvpJf ../../../lila-3.0.tar.xz . && cd -
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v1
        with:
          name: lila-server
          path: lila-3.0.tar.xz
